services:
  # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: |
      pip install -r requirements.txt &&
      python nltk_setup.py &&
      python download_models.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NLTK_DATA
        value: /opt/render/project/src/nltk_data
